export const DEDICATED_PROVIDER_PROFILES = {
  openai: {
    adapter: "openai",
    label: "OpenAI / ChatGPT",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    apiKeyEnv: "OPENAI_API_KEY",
    logoPath: "/provider-logos/openai.svg",
    docsUrl: "https://platform.openai.com/docs/api-reference/chat",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "o3-mini"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  gemini: {
    adapter: "gemini",
    label: "Google Gemini",
    type: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    apiKeyEnv: "GEMINI_API_KEY",
    docsUrl: "https://ai.google.dev/gemini-api/docs/image-generation",
    models: ["gemini-3.1-flash-lite-image", "gemini-3.1-flash-image", "gemini-3-pro-image", "gemini-2.5-flash-image"],
    supportsTools: false,
    supportsVision: true,
    supportsImageGeneration: true,
    officialApi: true,
    authModes: ["api-key", "oauth2-bearer"],
    oauthStatus: "official-google-cloud-oauth",
    authMode: "api-key",
  },
  anthropic: {
    adapter: "anthropic",
    label: "Anthropic / Claude",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    logoPath: "/provider-logos/anthropic.svg",
    docsUrl: "https://docs.anthropic.com/en/api/messages",
    models: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-3-5-haiku-latest"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  deepseek: {
    adapter: "openai",
    label: "DeepSeek",
    type: "openai",
    baseUrl: "https://api.deepseek.com/v1",
    apiKeyEnv: "DEEPSEEK_API_KEY",
    logoPath: "/provider-logos/deepseek.svg",
    docsUrl: "https://api-docs.deepseek.com/",
    models: ["deepseek-chat", "deepseek-reasoner"],
    supportsTools: true,
    supportsVision: false,
    officialApi: true,
    authModes: ["api-key"],
  },
  groq: {
    adapter: "openai",
    label: "Groq",
    type: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    apiKeyEnv: "GROQ_API_KEY",
    logoPath: "/provider-logos/groq.svg",
    docsUrl: "https://console.groq.com/docs/quickstart",
    models: ["llama-3.3-70b-versatile", "openai/gpt-oss-120b", "qwen/qwen3-32b"],
    supportsTools: true,
    supportsVision: false,
    officialApi: true,
    authModes: ["api-key"],
  },
  "xai-oauth": {
    adapter: "openai",
    label: "xAI / Grok OAuth (subscription)",
    type: "openai",
    baseUrl: "https://api.x.ai/v1",
    logoPath: "/provider-logos/grok.svg",
    docsUrl: "https://help.router-for.me/configuration/provider/xai",
    models: ["grok-4", "grok-4.3", "grok-build-0.1", "grok-imagine-image"],
    supportsTools: true,
    supportsVision: true,
    supportsImageGeneration: true,
    officialApi: "oauth-subscription",
    authModes: ["oauth2-pkce", "api-key"],
    oauthAuthUrl: "https://auth.x.ai/oauth2/authorize",
    oauthTokenUrl: "https://auth.x.ai/oauth2/token",
    oauthClientId: "b1a00492-073a-47ea-816f-4c329264a828",
    oauthPkce: true,
    oauthScopes: ["openid", "profile", "email", "offline_access", "grok-cli:access", "api:access"],
    availabilityNote: "OAuth requires an eligible SuperGrok/X Premium+ subscription or provider entitlement; this is not free/no-auth access.",
    subscriptionRequired: true,
  },
  perplexity: {
    adapter: "openai",
    label: "Perplexity",
    type: "openai",
    baseUrl: "https://api.perplexity.ai",
    apiKeyEnv: "PERPLEXITY_API_KEY",
    logoPath: "/provider-logos/perplexity.svg",
    docsUrl: "https://docs.perplexity.ai/",
    models: ["sonar", "sonar-pro", "sonar-reasoning-pro"],
    supportsTools: false,
    supportsVision: false,
    officialApi: true,
    authModes: ["api-key"],
  },
  mistral: {
    adapter: "openai",
    label: "Mistral AI",
    type: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    apiKeyEnv: "MISTRAL_API_KEY",
    logoPath: "/provider-logos/mistral.svg",
    docsUrl: "https://docs.mistral.ai/api/",
    models: ["mistral-large-latest", "mistral-small-latest", "codestral-latest"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key"],
  },
  cohere: {
    adapter: "openai",
    label: "Cohere",
    type: "openai",
    baseUrl: "https://api.cohere.com/compatibility/v1",
    apiKeyEnv: "COHERE_API_KEY",
    logoPath: "/provider-logos/cohere.svg",
    docsUrl: "https://docs.cohere.com/",
    models: ["command-a-03-2025", "command-r-plus"],
    supportsTools: true,
    supportsVision: false,
    officialApi: true,
    authModes: ["api-key"],
  },
  huggingface: {
    adapter: "openai",
    label: "Hugging Face Inference",
    type: "openai",
    baseUrl: "https://router.huggingface.co/v1",
    apiKeyEnv: "HUGGINGFACE_API_KEY",
    logoPath: "/provider-logos/huggingface.svg",
    docsUrl: "https://huggingface.co/docs/api-inference/",
    models: [],
    supportsTools: false,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key"],
  },
  "vertex-ai": {
    adapter: "gemini",
    label: "Google Vertex AI",
    type: "gemini",
    baseUrl: "https://us-central1-aiplatform.googleapis.com/v1",
    apiKeyEnv: "VERTEX_AI_API_KEY",
    logoPath: "/provider-logos/vertex-ai.svg",
    docsUrl: "https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/inference",
    models: ["gemini-2.5-pro", "gemini-2.5-flash"],
    supportsTools: true,
    supportsVision: true,
    supportsImageGeneration: true,
    officialApi: true,
    authModes: ["oauth2-bearer", "service-account"],
  },
  "azure-openai": {
    adapter: "openai",
    label: "Azure OpenAI",
    type: "openai",
    baseUrl: "https://example.openai.azure.com/openai/deployments/default",
    apiKeyEnv: "AZURE_OPENAI_API_KEY",
    logoPath: "/provider-logos/azure-openai.svg",
    docsUrl: "https://learn.microsoft.com/azure/ai-services/openai/",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key", "azure-ad"],
    requiresBaseUrl: true,
  },
  openrouter: {
    adapter: "openai",
    label: "OpenRouter",
    type: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    apiKeyEnv: "OPENROUTER_API_KEY",
    logoPath: "/provider-logos/openrouter.svg",
    docsUrl: "https://openrouter.ai/docs/quickstart",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key"],
  },
  together: {
    adapter: "openai",
    label: "Together AI",
    type: "openai",
    baseUrl: "https://api.together.xyz/v1",
    apiKeyEnv: "TOGETHER_API_KEY",
    logoPath: "/provider-logos/together.svg",
    docsUrl: "https://docs.together.ai/docs/quickstart",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key"],
  },
  fireworks: {
    adapter: "openai",
    label: "Fireworks AI",
    type: "openai",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    apiKeyEnv: "FIREWORKS_API_KEY",
    logoPath: "/provider-logos/fireworks.svg",
    docsUrl: "https://docs.fireworks.ai/tools-sdks/openai-compatibility",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key"],
  },
  cerebras: {
    adapter: "openai",
    label: "Cerebras",
    type: "openai",
    baseUrl: "https://api.cerebras.ai/v1",
    apiKeyEnv: "CEREBRAS_API_KEY",
    logoPath: "/provider-logos/cerebras.svg",
    docsUrl: "https://inference-docs.cerebras.ai/",
    models: [],
    supportsTools: true,
    supportsVision: false,
    officialApi: true,
    authModes: ["api-key"],
  },
  sambanova: {
    adapter: "openai",
    label: "SambaNova Cloud",
    type: "openai",
    baseUrl: "https://api.sambanova.ai/v1",
    apiKeyEnv: "SAMBANOVA_API_KEY",
    logoPath: "/provider-logos/sambanova.svg",
    docsUrl: "https://docs.sambanova.ai/cloud/docs/get-started/overview",
    models: [],
    supportsTools: true,
    supportsVision: false,
    officialApi: true,
    authModes: ["api-key"],
  },
  "nvidia-nim": {
    adapter: "openai",
    label: "NVIDIA NIM",
    type: "openai",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    apiKeyEnv: "NVIDIA_API_KEY",
    logoPath: "/provider-logos/nvidia.svg",
    docsUrl: "https://docs.api.nvidia.com/nim/reference/openai-compatibility",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key"],
  },
  "cloudflare-workers-ai": {
    adapter: "openai",
    label: "Cloudflare Workers AI",
    type: "openai",
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
    apiKeyEnv: "CLOUDFLARE_API_TOKEN",
    logoPath: "/provider-logos/cloudflare.svg",
    docsUrl: "https://developers.cloudflare.com/workers-ai/configuration/open-ai-compatibility/",
    models: [],
    supportsTools: false,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-token"],
    requiresBaseUrl: true,
    availabilityNote: "Enter the account-specific Workers AI base URL from the official Cloudflare dashboard.",
  },
  "vercel-ai-gateway": {
    adapter: "openai",
    label: "Vercel AI Gateway",
    type: "openai",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    apiKeyEnv: "AI_GATEWAY_API_KEY",
    logoPath: "/provider-logos/vercel.svg",
    docsUrl: "https://vercel.com/docs/ai-gateway",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["api-key"],
  },
  ollama: {
    adapter: "openai",
    label: "Ollama Local",
    type: "openai",
    baseUrl: "http://127.0.0.1:11434/v1",
    logoPath: "/provider-logos/ollama.svg",
    docsUrl: "https://ollama.com/blog/openai-compatibility",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: "local-openapi",
    localOnly: true,
    allowNoAuth: true,
    authModes: ["none"],
  },
  lmstudio: {
    adapter: "openai",
    label: "LM Studio Local",
    type: "openai",
    baseUrl: "http://127.0.0.1:1234/v1",
    logoPath: "/provider-logos/lmstudio.svg",
    docsUrl: "https://lmstudio.ai/docs/developer/openai-compat",
    models: [],
    supportsTools: true,
    supportsVision: true,
    officialApi: "local-openapi",
    localOnly: true,
    allowNoAuth: true,
    authModes: ["none"],
  },
  aihorde: {
    adapter: "openai",
    label: "AI Horde (anonymous public API)",
    type: "openai",
    logoPath: "/provider-logos/aihorde.svg",
    docsUrl: "https://aihorde.net/api",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "documented-public-api-non-openai",
    authModes: ["none", "optional-api-key"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "Anonymous API is documented, but this gateway has no native AI Horde adapter yet; add an authorized compatible bridge before activation.",
  },
  "opencode-zen": {
    adapter: "openai",
    label: "OpenCode Zen (free catalog candidate)",
    type: "openai",
    logoPath: "/provider-logos/opencode.svg",
    docsUrl: "https://opencode.ai/zen",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "documented-endpoint-only",
    authModes: ["documented-endpoint-only"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "Free catalog entry only; activate after adding the provider-documented endpoint and reviewing current terms.",
  },
  "duckduckgo-web": {
    adapter: "openai",
    label: "DuckDuckGo AI Chat (catalog candidate)",
    type: "openai",
    logoPath: "/provider-logos/duckduckgo.svg",
    docsUrl: "https://duckduckgo.com/duckchat",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "web-app-only",
    authModes: ["documented-endpoint-only"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "Catalog-only: no automated web-chat querying or hidden endpoint capture is enabled.",
  },
  qwen: {
    adapter: "qwen",
    label: "Qwen / Alibaba ModelStudio",
    type: "openai",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    apiKeyEnv: "DASHSCOPE_API_KEY",
    logoPath: "/provider-logos/qwen.svg",
    docsUrl: "https://qwenlm.github.io/qwen-code-docs/en/users/configuration/auth/",
    models: ["qwen3.7-plus", "qwen3.6-plus", "qwen3.5-plus", "qwen3.5-flash", "qwen3-max", "qwen3-vl-plus", "qwen3-vl-flash", "qwen3-coder-plus"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["standard-api-key", "coding-plan-api-key"],
    oauthStatus: "discontinued-2026-04-15",
  },
  manus: {
    adapter: "manus",
    label: "Manus Open App",
    type: "custom",
    baseUrl: "https://api.manus.ai/v2",
    docsUrl: "https://open.manus.ai/docs/v2/open-app",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: true,
    oauthOnly: true,
    oauthPkce: true,
    oauthAuthUrl: "https://manus.im/openapi/oauth",
    oauthTokenUrl: "https://api.manus.ai/oauth/token",
    oauthClientIdEnv: "MANUS_OAUTH_CLIENT_ID",
    oauthClientSecretEnv: "MANUS_OAUTH_CLIENT_SECRET",
    oauthScopes: ["create_task"],
    authModes: ["oauth2-authorization-code-pkce", "api-key"],
    oauthStatus: "official-open-app-oauth-team-only",
  },
  mimo: {
    adapter: "openai",
    label: "Xiaomi MiMo",
    type: "openai",
    baseUrl: "https://api.xiaomimimo.com/v1",
    apiKeyEnv: "MIMO_API_KEY",
    apiKeyHeader: "api-key",
    docsUrl: "https://mimo.mi.com/docs/quick-start/first-api-call",
    models: ["mimo-v2.5-pro", "mimo-v2.5"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["standard-api-key", "token-plan-api-key"],
    oauthStatus: "official-login-creates-api-key",
  },
  kimi: {
    adapter: "openai",
    label: "Kimi / Moonshot",
    type: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    apiKeyEnv: "MOONSHOT_API_KEY",
    logoPath: "/provider-logos/kimi.svg",
    docsUrl: "https://platform.kimi.ai/docs/api/chat",
    models: ["kimi-k3", "kimi-k2.7-code", "kimi-k2.6", "kimi-k2.5", "moonshot-v1-128k"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  grok: {
    adapter: "openai",
    label: "Grok / xAI",
    type: "openai",
    baseUrl: "https://api.x.ai/v1",
    apiKeyEnv: "XAI_API_KEY",
    logoPath: "/provider-logos/grok.svg",
    docsUrl: "https://docs.x.ai/developers/models",
    models: ["grok-4.5", "grok-4.1-fast"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  "aws-bedrock": {
    adapter: "bedrock",
    label: "AWS Bedrock",
    type: "bedrock",
    baseUrl: null,
    logoPath: "/provider-logos/aws-bedrock.svg",
    docsUrl: "https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html",
    models: ["anthropic.claude-3-5-sonnet-20241022-v2:0", "amazon.nova-pro-v1:0", "meta.llama3-3-70b-instruct-v1:0"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    region: "us-east-1",
    accessKeyEnv: "AWS_ACCESS_KEY_ID",
    secretKeyEnv: "AWS_SECRET_ACCESS_KEY",
    sessionTokenEnv: "AWS_SESSION_TOKEN",
  },
  gitlab: {
    adapter: "gitlab",
    label: "GitLab Duo",
    type: "gitlab",
    baseUrl: "https://gitlab.example.com/api/v4",
    apiKeyEnv: "GITLAB_TOKEN",
    logoPath: "/provider-logos/gitlab.svg",
    docsUrl: "https://docs.gitlab.com/api/chat/",
    models: ["duo-chat"],
    supportsTools: false,
    supportsVision: false,
    officialApi: "self-managed-only",
    requiresBaseUrl: true,
  },
  lovable: {
    adapter: "openai",
    label: "Lovable (custom endpoint)",
    type: "openai",
    apiKeyEnv: "LOVABLE_API_KEY",
    logoPath: "/provider-logos/lovable.svg",
    docsUrl: "https://docs.lovable.dev/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    requiresBaseUrl: true,
  },
  kiro: {
    adapter: "openai",
    label: "Kiro (authorized compatible endpoint)",
    type: "openai",
    apiKeyEnv: "KIRO_API_KEY",
    logoPath: "/provider-logos/kiro.svg",
    docsUrl: "https://kiro.dev/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    requiresBaseUrl: true,
    authModes: ["bearer-token", "api-key"],
    authMode: "bearer-token",
    apiKeyHeader: "authorization",
  },
  opencode: {
    adapter: "openai",
    label: "OpenCode local server",
    type: "openai",
    baseUrl: "http://127.0.0.1:4096/v1",
    logoPath: "/provider-logos/opencode.svg",
    docsUrl: "https://opencode.ai/docs/server/",
    models: [],
    supportsTools: true,
    supportsVision: false,
    officialApi: "local-openapi",
    localOnly: true,
    allowNoAuth: true,
  },
  "opencode-free": {
    adapter: "openai",
    label: "OpenCode Free (catalog candidate)",
    type: "openai",
    logoPath: "/provider-logos/opencode.svg",
    docsUrl: "https://opencode.ai/docs/",
    models: [],
    supportsTools: true,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    authModes: ["documented-endpoint-only"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "No remote endpoint is bundled; add an endpoint documented by the provider.",
  },
  felo: {
    adapter: "openai",
    label: "Felo (free catalog candidate)",
    type: "openai",
    logoPath: "/provider-logos/felo.svg",
    docsUrl: "https://felo.ai/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    authModes: ["documented-endpoint-only"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "Requires a provider-documented API endpoint; no web-app traffic capture is used.",
  },
  pollinations: {
    adapter: "openai",
    label: "Pollinations (free catalog candidate)",
    type: "openai",
    logoPath: "/provider-logos/pollinations.svg",
    docsUrl: "https://pollinations.ai/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    authModes: ["documented-endpoint-only"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "Requires an explicitly documented API route and current terms review.",
  },
  qoder: {
    adapter: "openai",
    label: "Qoder (free catalog candidate)",
    type: "openai",
    logoPath: "/provider-logos/qoder.svg",
    docsUrl: "https://qoder.com/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    authModes: ["documented-endpoint-only"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "No account/session endpoint is imported; configure only an authorized API.",
  },
  kilo: {
    adapter: "openai",
    label: "Kilo Code (free catalog candidate)",
    type: "openai",
    logoPath: "/provider-logos/kilo.svg",
    docsUrl: "https://kilocode.ai/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    authModes: ["documented-endpoint-only"],
    freeTierCatalog: true,
    catalogOnly: true,
    requiresBaseUrl: true,
    availabilityNote: "Requires an authorized, documented endpoint; no session scraping or MITM is supported.",
  },
  notion: {
    adapter: "notion",
    label: "Notion Workspace",
    type: "connector",
    baseUrl: "https://api.notion.com/v1",
    logoPath: "/provider-logos/notion.svg",
    docsUrl: "https://developers.notion.com/guides/get-started/authorization",
    models: [],
    supportsTools: true,
    supportsVision: false,
    officialApi: true,
    connectorOnly: true,
    connectorType: "workspace",
    apiVersion: "2026-03-11",
    oauthAuthUrl: "https://api.notion.com/v1/oauth/authorize",
    oauthTokenUrl: "https://api.notion.com/v1/oauth/token",
    oauthClientIdEnv: "NOTION_OAUTH_CLIENT_ID",
    oauthClientSecretEnv: "NOTION_OAUTH_CLIENT_SECRET",
    oauthTokenAuth: "basic",
    oauthTokenContentType: "json",
    oauthQueryParams: { owner: "user" },
    authModes: ["oauth2-authorization-code", "personal-access-token", "internal-connection-token"],
    availabilityNote: "Workspace connector only. It does not expose Notion AI as an OpenAI-compatible model.",
  },
  windsurf: {
    adapter: "windsurf",
    label: "Windsurf Enterprise Analytics",
    type: "connector",
    baseUrl: "https://server.codeium.com/api/v1",
    logoPath: "/provider-logos/windsurf.svg",
    docsUrl: "https://docs.windsurf.com/windsurf/accounts/api-reference/api-introduction",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "enterprise-service-api",
    connectorOnly: true,
    connectorType: "analytics",
    serviceKeyEnv: "WINDSURF_SERVICE_KEY",
    authModes: ["service-key"],
    availabilityNote: "Official service-key API is for enterprise usage/configuration analytics, not external model inference.",
  },
};

export function getDedicatedProviderProfile(id) {
  return DEDICATED_PROVIDER_PROFILES[String(id || "").trim().toLowerCase()] || null;
}

export function listDedicatedProviderProfiles() {
  return Object.entries(DEDICATED_PROVIDER_PROFILES).map(([id, profile]) => ({ id, ...profile }));
}
