export const DEDICATED_PROVIDER_PROFILES = {
  openai: {
    adapter: "openai",
    label: "OpenAI / ChatGPT",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    apiKeyEnv: "OPENAI_API_KEY",
    logoPath: "/provider-logos/openai.svg",
    docsUrl: "https://platform.openai.com/docs/api-reference/chat",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "o3-mini"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  anthropic: {
    adapter: "anthropic",
    label: "Anthropic / Claude",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    logoPath: "/provider-logos/anthropic.svg",
    docsUrl: "https://docs.anthropic.com/en/api/messages",
    models: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-3-5-haiku-latest"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  qwen: {
    adapter: "qwen",
    label: "Qwen / Alibaba ModelStudio",
    type: "openai",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    apiKeyEnv: "DASHSCOPE_API_KEY",
    logoPath: "/provider-logos/qwen.svg",
    docsUrl: "https://qwenlm.github.io/qwen-code-docs/en/users/configuration/auth/",
    models: ["qwen3.7-plus", "qwen3.6-plus", "qwen3.5-plus", "qwen3.5-flash", "qwen3-max", "qwen3-vl-plus", "qwen3-vl-flash", "qwen3-coder-plus"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["standard-api-key", "coding-plan-api-key"],
    oauthStatus: "discontinued-2026-04-15",
  },
  manus: {
    adapter: "manus",
    label: "Manus Open App",
    type: "custom",
    baseUrl: "https://api.manus.ai/v2",
    docsUrl: "https://open.manus.ai/docs/v2/open-app",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: true,
    oauthOnly: true,
    oauthPkce: true,
    oauthAuthUrl: "https://manus.im/openapi/oauth",
    oauthTokenUrl: "https://api.manus.ai/oauth/token",
    oauthClientIdEnv: "MANUS_OAUTH_CLIENT_ID",
    oauthClientSecretEnv: "MANUS_OAUTH_CLIENT_SECRET",
    oauthScopes: ["create_task"],
    authModes: ["oauth2-authorization-code-pkce", "api-key"],
    oauthStatus: "official-open-app-oauth-team-only",
  },
  mimo: {
    adapter: "openai",
    label: "Xiaomi MiMo",
    type: "openai",
    baseUrl: "https://api.xiaomimimo.com/v1",
    apiKeyEnv: "MIMO_API_KEY",
    apiKeyHeader: "api-key",
    docsUrl: "https://mimo.mi.com/docs/quick-start/first-api-call",
    models: ["mimo-v2.5-pro", "mimo-v2.5"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    authModes: ["standard-api-key", "token-plan-api-key"],
    oauthStatus: "official-login-creates-api-key",
  },
  kimi: {
    adapter: "openai",
    label: "Kimi / Moonshot",
    type: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    apiKeyEnv: "MOONSHOT_API_KEY",
    logoPath: "/provider-logos/kimi.svg",
    docsUrl: "https://platform.kimi.ai/docs/api/chat",
    models: ["kimi-k3", "kimi-k2.7-code", "kimi-k2.6", "kimi-k2.5", "moonshot-v1-128k"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  grok: {
    adapter: "openai",
    label: "Grok / xAI",
    type: "openai",
    baseUrl: "https://api.x.ai/v1",
    apiKeyEnv: "XAI_API_KEY",
    logoPath: "/provider-logos/grok.svg",
    docsUrl: "https://docs.x.ai/developers/models",
    models: ["grok-4.5", "grok-4.1-fast"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  "aws-bedrock": {
    adapter: "bedrock",
    label: "AWS Bedrock",
    type: "bedrock",
    baseUrl: null,
    logoPath: "/provider-logos/aws-bedrock.svg",
    docsUrl: "https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_Converse.html",
    models: ["anthropic.claude-3-5-sonnet-20241022-v2:0", "amazon.nova-pro-v1:0", "meta.llama3-3-70b-instruct-v1:0"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
    region: "us-east-1",
    accessKeyEnv: "AWS_ACCESS_KEY_ID",
    secretKeyEnv: "AWS_SECRET_ACCESS_KEY",
    sessionTokenEnv: "AWS_SESSION_TOKEN",
  },
  gitlab: {
    adapter: "gitlab",
    label: "GitLab Duo",
    type: "gitlab",
    baseUrl: "https://gitlab.example.com/api/v4",
    apiKeyEnv: "GITLAB_TOKEN",
    logoPath: "/provider-logos/gitlab.svg",
    docsUrl: "https://docs.gitlab.com/api/chat/",
    models: ["duo-chat"],
    supportsTools: false,
    supportsVision: false,
    officialApi: "self-managed-only",
    requiresBaseUrl: true,
  },
  lovable: {
    adapter: "openai",
    label: "Lovable (custom endpoint)",
    type: "openai",
    apiKeyEnv: "LOVABLE_API_KEY",
    logoPath: "/provider-logos/lovable.svg",
    docsUrl: "https://docs.lovable.dev/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    requiresBaseUrl: true,
  },
  kiro: {
    adapter: "openai",
    label: "Kiro (authorized compatible endpoint)",
    type: "openai",
    apiKeyEnv: "KIRO_API_KEY",
    logoPath: "/provider-logos/kiro.svg",
    docsUrl: "https://kiro.dev/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    requiresBaseUrl: true,
  },
  opencode: {
    adapter: "openai",
    label: "OpenCode local server",
    type: "openai",
    baseUrl: "http://127.0.0.1:4096/v1",
    logoPath: "/provider-logos/opencode.svg",
    docsUrl: "https://opencode.ai/docs/server/",
    models: [],
    supportsTools: true,
    supportsVision: false,
    officialApi: "local-openapi",
    localOnly: true,
    allowNoAuth: true,
  },
};

export function getDedicatedProviderProfile(id) {
  return DEDICATED_PROVIDER_PROFILES[String(id || "").trim().toLowerCase()] || null;
}

export function listDedicatedProviderProfiles() {
  return Object.entries(DEDICATED_PROVIDER_PROFILES).map(([id, profile]) => ({ id, ...profile }));
}
