export const DEDICATED_PROVIDER_PROFILES = {
  openai: {
    adapter: "openai",
    label: "OpenAI / ChatGPT",
    type: "openai",
    baseUrl: "https://api.openai.com/v1",
    apiKeyEnv: "OPENAI_API_KEY",
    logoPath: "/provider-logos/openai.svg",
    docsUrl: "https://platform.openai.com/docs/api-reference/chat",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4.1", "o3-mini"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  anthropic: {
    adapter: "anthropic",
    label: "Anthropic / Claude",
    type: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    apiKeyEnv: "ANTHROPIC_API_KEY",
    logoPath: "/provider-logos/anthropic.svg",
    docsUrl: "https://docs.anthropic.com/en/api/messages",
    models: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-3-5-haiku-latest"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  qwen: {
    adapter: "openai",
    label: "Qwen / DashScope",
    type: "openai",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    apiKeyEnv: "DASHSCOPE_API_KEY",
    logoPath: "/provider-logos/qwen.svg",
    docsUrl: "https://www.alibabacloud.com/help/en/model-studio/compatibility-of-openai-with-dashscope",
    models: ["qwen-plus", "qwen-max", "qwen-turbo", "qwen-vl-max"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  kimi: {
    adapter: "openai",
    label: "Kimi / Moonshot",
    type: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    apiKeyEnv: "MOONSHOT_API_KEY",
    logoPath: "/provider-logos/kimi.svg",
    docsUrl: "https://platform.kimi.ai/docs/api/chat",
    models: ["kimi-k3", "kimi-k2.7-code", "kimi-k2.6", "kimi-k2.5", "moonshot-v1-128k"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  grok: {
    adapter: "openai",
    label: "Grok / xAI",
    type: "openai",
    baseUrl: "https://api.x.ai/v1",
    apiKeyEnv: "XAI_API_KEY",
    logoPath: "/provider-logos/grok.svg",
    docsUrl: "https://docs.x.ai/developers/models",
    models: ["grok-4.5", "grok-4.1-fast"],
    supportsTools: true,
    supportsVision: true,
    officialApi: true,
  },
  gitlab: {
    adapter: "gitlab",
    label: "GitLab Duo",
    type: "gitlab",
    baseUrl: "https://gitlab.example.com/api/v4",
    apiKeyEnv: "GITLAB_TOKEN",
    logoPath: "/provider-logos/gitlab.svg",
    docsUrl: "https://docs.gitlab.com/api/chat/",
    models: ["duo-chat"],
    supportsTools: false,
    supportsVision: false,
    officialApi: "self-managed-only",
    requiresBaseUrl: true,
  },
  lovable: {
    adapter: "openai",
    label: "Lovable (custom endpoint)",
    type: "openai",
    apiKeyEnv: "LOVABLE_API_KEY",
    logoPath: "/provider-logos/lovable.svg",
    docsUrl: "https://docs.lovable.dev/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    requiresBaseUrl: true,
  },
  kiro: {
    adapter: "openai",
    label: "Kiro (authorized compatible endpoint)",
    type: "openai",
    apiKeyEnv: "KIRO_API_KEY",
    logoPath: "/provider-logos/kiro.svg",
    docsUrl: "https://kiro.dev/",
    models: [],
    supportsTools: false,
    supportsVision: false,
    officialApi: "custom-endpoint-only",
    requiresBaseUrl: true,
  },
  opencode: {
    adapter: "openai",
    label: "OpenCode local server",
    type: "openai",
    baseUrl: "http://127.0.0.1:4096/v1",
    logoPath: "/provider-logos/opencode.svg",
    docsUrl: "https://opencode.ai/docs/server/",
    models: [],
    supportsTools: true,
    supportsVision: false,
    officialApi: "local-openapi",
    localOnly: true,
    allowNoAuth: true,
  },
};

export function getDedicatedProviderProfile(id) {
  return DEDICATED_PROVIDER_PROFILES[String(id || "").trim().toLowerCase()] || null;
}

export function listDedicatedProviderProfiles() {
  return Object.entries(DEDICATED_PROVIDER_PROFILES).map(([id, profile]) => ({ id, ...profile }));
}
