import { gatewayError } from "./openai.js";

const MAX_IMAGES_PER_REQUEST = 4;
const MAX_IMAGE_BYTES = 5 * 1024 * 1024;
const DATA_IMAGE_PATTERN = /^data:(image\/(?:png|jpeg|webp|gif));base64,([A-Za-z0-9+/=\s]+)$/i;

export function validateImageUrl(value) {
  const match = DATA_IMAGE_PATTERN.exec(String(value || ""));
  if (!match) {
    throw gatewayError("Vision fallback accepts only inline PNG, JPEG, WebP, or GIF data URLs; remote image URLs are disabled", 400, "unsupported_image_source");
  }
  const bytes = Buffer.byteLength(match[2].replace(/\s/g, ""), "base64");
  if (bytes === 0 || bytes > MAX_IMAGE_BYTES) {
    throw gatewayError(`Each inline image must be between 1 byte and ${MAX_IMAGE_BYTES} bytes`, 400, "invalid_image_size");
  }
  return { mediaType: match[1].toLowerCase(), data: match[2].replace(/\s/g, ""), bytes };
}

export function countImages(messages) {
  return messages.reduce((count, message) => {
    if (!Array.isArray(message?.content)) return count;
    return count + message.content.filter((part) => part?.type === "image_url").length;
  }, 0);
}

export async function convertImagesToText(messages, describeImage) {
  const imageCount = countImages(messages);
  if (imageCount > MAX_IMAGES_PER_REQUEST) {
    throw gatewayError(`At most ${MAX_IMAGES_PER_REQUEST} images can be sent in one request`, 400, "invalid_image_count");
  }
  if (imageCount === 0) return messages;

  const transformed = [];
  for (const message of messages) {
    if (!Array.isArray(message?.content)) {
      transformed.push(message);
      continue;
    }

    const nextContent = [];
    for (const part of message.content) {
      if (part?.type !== "image_url") {
        nextContent.push(part);
        continue;
      }
      const image = validateImageUrl(part.image_url?.url);
      const description = await describeImage(image);
      nextContent.push({
        type: "text",
        text: `[Image description generated by the configured vision provider]\n${description}`,
      });
    }
    transformed.push({ ...message, content: nextContent });
  }
  return transformed;
}

export const __testables = { DATA_IMAGE_PATTERN };
